language: ruby
env:
# compiled binary lacks libxml2 integration
# - EVM_EMACS=emacs-24.3-bin
- EVM_EMACS=emacs-git-snapshot
before_install:
- sudo apt-get install texinfo
- sudo apt-get install libxml2-dev
- sudo apt-get install libxpm-dev
- sudo apt-get install libgif-dev
install:
- sudo mkdir /usr/local/evm
- sudo chown $(id -u):$(id -g) /usr/local/evm
- curl -fsSkL https://raw.github.com/rejeep/evm/master/go
- curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
- export PATH="$HOME/.evm/bin:$PATH"
- evm install $EVM_EMACS --use
- which emacs
- emacs --version
- curl -fsSkL https://raw.github.com/cask/cask/master/go | python
- export PATH="$HOME/.cask/bin:$PATH"
- cask
script:
- cask exec ert-runner
