(deftheme lloyd-custom-zenburn
  "Created 2014-04-14.")

(custom-theme-set-variables
 'lloyd-custom-zenburn
 '(autopair-autowrap t)
 '(autopair-global-mode t)
 '(confirm-kill-emacs nil)
 '(custom-safe-themes (quote ("e7af2246eff56872b197ee7493563a5ffa26022ca813b02c28c8e9f19f742678" "a53714de04cd4fdb92ed711ae479f6a1d7d5f093880bfd161467c3f589725453" "11d069fbfb0510e2b32a5787e26b762898c7e480364cbc0779fe841662e4cf5d" default)))
 '(delete-by-moving-to-trash t)
 '(global-auto-complete-mode t)
 '(global-discover-mode t)
 '(ido-enable-flex-matching t)
 '(indent-tabs-mode nil)
 '(package-archives (quote (("gnu" . "http://elpa.gnu.org/packages/") ("marmalade" . "http://marmalade-repo.org/packages/") ("melpa" . "http://melpa.milkbox.net/packages/"))))
 '(speedbar-track-mouse-flag t)
 '(tab-always-indent nil)
 '(track-eol t)
 '(trash-directory "~/.trash")
 '(undo-limit 100000))

(custom-theme-set-faces
 'lloyd-custom-zenburn
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#F0DFAF" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#D0BF8F" :underline t :weight normal))))
 '(cursor ((t (:foreground "#DCDCCC" :background "#FFFFEF"))))
 '(escape-glyph ((t (:foreground "#F0DFAF" :bold t))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(header-line ((t (:foreground "#F0DFAF" :background "#2B2B2B" :box (:line-width -1 :style released-button)))))
 '(highlight ((t (:background "#383838"))))
 '(success ((t (:foreground "#7F9F7F" :weight bold))))
 '(warning ((t (:foreground "#DFAF8F" :weight bold))))
 '(match ((t (:background "#2B2B2B" :foreground "#DFAF8F" :weight bold))))
 '(isearch ((t (:foreground "#D0BF8F" :weight bold :background "#5F5F5F"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#8C5353"))))
 '(lazy-highlight ((t (:foreground "#D0BF8F" :weight bold :background "#383838"))))
 '(menu ((t (:foreground "#DCDCCC" :background "#3F3F3F"))))
 '(minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#8FB28F" :background "#2B2B2B" :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 '(mode-line-buffer-id ((t (:foreground "#F0DFAF" :weight bold))))
 '(mode-line-inactive ((t (:foreground "#5F7F5F" :background "#383838" :box (:line-width -1 :style released-button)))))
 '(region ((((class color) (min-colors 89)) (:background "#2B2B2B")) (t :inverse-video t)))
 '(secondary-selection ((t (:background "#5F5F5F"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(vertical-border ((t (:foreground "#DCDCCC"))))
 '(font-lock-builtin-face ((t (:foreground "#DCDCCC" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#7F9F7F" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:foreground "#D0BF8F" :weight bold))))
 '(ac-candidate-face ((t (:background "#6F6F6F" :foreground "#000000"))))
 '(ac-selection-face ((t (:background "#4C7073" :foreground "#DCDCCC"))))
 '(popup-tip-face ((t (:background "#D0BF8F" :foreground "#000000"))))
 '(popup-scroll-bar-foreground-face ((t (:background "#366060"))))
 '(popup-scroll-bar-background-face ((t (:background "#2B2B2B"))))
 '(popup-isearch-match ((t (:background "#3F3F3F" :foreground "#DCDCCC"))))
 '(ido-first-match ((t (:foreground "#F0DFAF" :weight bold))))
 '(ido-only-match ((t (:foreground "#DFAF8F" :weight bold))))
 '(ido-subdir ((t (:foreground "#F0DFAF"))))
 '(ido-indicator ((t (:foreground "#F0DFAF" :background "#8C5353"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#DCDCCC"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#BFEBBF"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#D0BF8F"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#93E0E3"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#9FC59F"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#94BFF3"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#E0CF9F"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#8FB28F"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#6CA0A3"))))
 '(show-paren-mismatch ((t (:foreground "#DCA3A3" :background "#6F6F6F" :weight bold))))
 '(show-paren-match ((t (:background "#6F6F6F" :weight bold))))
 '(speedbar-button-face ((t (:foreground "#9FC59F"))))
 '(speedbar-directory-face ((t (:foreground "#93E0E3"))))
 '(speedbar-file-face ((t (:foreground "#DCDCCC"))))
 '(speedbar-highlight-face ((t (:foreground "#3F3F3F" :background "#9FC59F"))))
 '(speedbar-selected-face ((t (:foreground "#CC9393"))))
 '(speedbar-separator-face ((t (:foreground "#3F3F3F" :background "#7CB8BB"))))
 '(speedbar-tag-face ((t (:foreground "#F0DFAF"))))
 '(default ((t (:foreground "#DCDCCC" :background "#3F3F3F")))))

(provide-theme 'lloyd-custom-zenburn)
